"""Add subscription and payment models

Revision ID: 2326c42ca838
Revises: e4f5g6h7i8j9
Create Date: 2025-12-20 23:36:31.451926

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2326c42ca838'
down_revision = 'e4f5g6h7i8j9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_monthly', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_yearly', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('limits', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_plans_id'), 'subscription_plans', ['id'], unique=False)
    op.create_index(op.f('ix_subscription_plans_name'), 'subscription_plans', ['name'], unique=True)
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('requests_count', sa.Integer(), nullable=False),
    sa.Column('requests_count_monthly', sa.Integer(), nullable=False),
    sa.Column('last_reset_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_id'), 'api_keys', ['id'], unique=False)
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('user_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('billing_cycle', sa.String(length=20), nullable=False),
    sa.Column('current_period_start', sa.DateTime(), nullable=False),
    sa.Column('current_period_end', sa.DateTime(), nullable=False),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('canceled_at', sa.DateTime(), nullable=True),
    sa.Column('trial_start', sa.DateTime(), nullable=True),
    sa.Column('trial_end', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_subscriptions_id'), 'user_subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_user_subscriptions_plan_id'), 'user_subscriptions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_user_subscriptions_stripe_customer_id'), 'user_subscriptions', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('ix_user_subscriptions_stripe_subscription_id'), 'user_subscriptions', ['stripe_subscription_id'], unique=True)
    op.create_index(op.f('ix_user_subscriptions_user_id'), 'user_subscriptions', ['user_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_invoice_id', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('payment_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['user_subscriptions.id'], ondelete='SET_NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_stripe_invoice_id'), 'payments', ['stripe_invoice_id'], unique=False)
    op.create_index(op.f('ix_payments_stripe_payment_intent_id'), 'payments', ['stripe_payment_intent_id'], unique=True)
    op.create_index(op.f('ix_payments_subscription_id'), 'payments', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.drop_index(op.f('backorders_domain_id_index'), table_name='backorders')
    op.drop_index(op.f('backorders_status_index'), table_name='backorders')
    op.drop_index(op.f('backorders_user_id_domain_id_unique'), table_name='backorders')
    op.drop_table('backorders')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('watchlists_domain_id_foreign'), table_name='watchlists')
    op.drop_index(op.f('watchlists_notify_drop_index'), table_name='watchlists')
    op.drop_index(op.f('watchlists_notify_score_change_index'), table_name='watchlists')
    op.drop_index(op.f('watchlists_user_id_domain_id_unique'), table_name='watchlists')
    op.drop_table('watchlists')
    op.drop_index(op.f('domain_ai_scores_ai_decision_index'), table_name='domain_ai_scores')
    op.drop_index(op.f('domain_ai_scores_domain_id_foreign'), table_name='domain_ai_scores')
    op.drop_index(op.f('domain_ai_scores_investment_score_index'), table_name='domain_ai_scores')
    op.drop_index(op.f('domain_ai_scores_valuation_mid_index'), table_name='domain_ai_scores')
    op.drop_table('domain_ai_scores')
    op.drop_index(op.f('bulk_imports_created_at_index'), table_name='bulk_imports')
    op.drop_index(op.f('bulk_imports_status_index'), table_name='bulk_imports')
    op.drop_index(op.f('bulk_imports_user_id_foreign'), table_name='bulk_imports')
    op.drop_table('bulk_imports')
    op.drop_table('migrations')
    op.drop_index(op.f('user_settings_user_id_unique'), table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_index(op.f('domain_score_history_captured_at_index'), table_name='domain_score_history')
    op.drop_index(op.f('domain_score_history_domain_id_captured_at_index'), table_name='domain_score_history')
    op.drop_table('domain_score_history')
    op.drop_index(op.f('domains_backlinks_count_index'), table_name='domains')
    op.drop_index(op.f('domains_brandability_score_index'), table_name='domains')
    op.drop_index(op.f('domains_drop_date_index'), table_name='domains')
    op.drop_index(op.f('domains_dropped_at_index'), table_name='domains')
    op.drop_index(op.f('domains_fqdn_index'), table_name='domains')
    op.drop_index(op.f('domains_name_unique'), table_name='domains')
    op.drop_index(op.f('domains_source_index'), table_name='domains')
    op.drop_index(op.f('domains_spam_score_index'), table_name='domains')
    op.drop_index(op.f('domains_status_index'), table_name='domains')
    op.drop_index(op.f('domains_tld_index'), table_name='domains')
    op.drop_table('domains')
    op.drop_index(op.f('domain_metrics_archive_snapshots_count_index'), table_name='domain_metrics')
    op.drop_index(op.f('domain_metrics_backlink_quality_score_index'), table_name='domain_metrics')
    op.drop_index(op.f('domain_metrics_domain_id_foreign'), table_name='domain_metrics')
    op.drop_index(op.f('domain_metrics_ref_domains_index'), table_name='domain_metrics')
    op.drop_index(op.f('domain_metrics_spam_score_index'), table_name='domain_metrics')
    op.drop_table('domain_metrics')
    op.drop_index(op.f('sessions_last_activity_index'), table_name='sessions')
    op.drop_index(op.f('sessions_user_id_index'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('user_favorite_domains_domain_id_index'), table_name='user_favorite_domains')
    op.drop_index(op.f('user_favorite_domains_user_id_domain_id_unique'), table_name='user_favorite_domains')
    op.drop_index(op.f('user_favorite_domains_user_id_index'), table_name='user_favorite_domains')
    op.drop_table('user_favorite_domains')
    op.drop_index(op.f('domain_sources_is_active_index'), table_name='domain_sources')
    op.drop_index(op.f('domain_sources_name_unique'), table_name='domain_sources')
    op.drop_index(op.f('domain_sources_type_index'), table_name='domain_sources')
    op.drop_table('domain_sources')
    op.drop_index(op.f('user_notification_settings_user_id_unique'), table_name='user_notification_settings')
    op.drop_table('user_notification_settings')
    op.drop_index(op.f('domain_filters_is_public_index'), table_name='domain_filters')
    op.drop_index(op.f('domain_filters_user_id_index'), table_name='domain_filters')
    op.drop_table('domain_filters')
    op.create_foreign_key(None, 'cron_job_logs', 'cron_jobs', ['job_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_domain_histories_domain'), 'domain_histories', ['domain'], unique=True)
    op.alter_column('dropped_domains', 'domain',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=191),
               existing_nullable=False)
    op.create_index('idx_domain_drop_date', 'dropped_domains', ['domain', 'drop_date'], unique=True)
    op.create_index(op.f('ix_dropped_domains_domain'), 'dropped_domains', ['domain'], unique=False)
    op.create_index(op.f('ix_dropped_domains_drop_date'), 'dropped_domains', ['drop_date'], unique=False)
    op.create_index(op.f('ix_dropped_domains_id'), 'dropped_domains', ['id'], unique=False)
    op.create_index(op.f('ix_dropped_domains_tld_id'), 'dropped_domains', ['tld_id'], unique=False)
    op.create_foreign_key(None, 'dropped_domains', 'tlds', ['tld_id'], ['id'])
    op.create_foreign_key(None, 'notification_settings', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('notifications', sa.Column('channel', sa.Enum('EMAIL', 'TELEGRAM', 'DISCORD', 'WEBHOOK', name='notificationchannel'), nullable=False))
    op.add_column('notifications', sa.Column('subject', sa.String(length=255), nullable=True))
    op.add_column('notifications', sa.Column('data', sa.Text(), nullable=True))
    op.add_column('notifications', sa.Column('recipient', sa.String(length=500), nullable=True))
    op.add_column('notifications', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('notifications', sa.Column('retry_count', sa.Integer(), nullable=False))
    op.add_column('notifications', sa.Column('sent_at', sa.DateTime(), nullable=True))
    op.alter_column('notifications', 'id',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('notifications', 'user_id',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('notifications', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False)
    op.drop_index(op.f('notifications_created_at_index'), table_name='notifications')
    op.drop_index(op.f('notifications_status_index'), table_name='notifications')
    op.drop_index(op.f('notifications_type_index'), table_name='notifications')
    op.drop_index(op.f('notifications_user_id_foreign'), table_name='notifications')
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('notifications', 'updated_at')
    op.drop_column('notifications', 'type')
    op.drop_column('notifications', 'read_at')
    op.create_foreign_key(None, 'user_favorites', 'dropped_domains', ['domain_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_favorites', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_watchlists', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_watchlists', type_='foreignkey')
    op.drop_constraint(None, 'user_favorites', type_='foreignkey')
    op.drop_constraint(None, 'user_favorites', type_='foreignkey')
    op.add_column('notifications', sa.Column('read_at', mysql.TIMESTAMP(), nullable=True))
    op.add_column('notifications', sa.Column('type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False))
    op.add_column('notifications', sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True))
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.create_index(op.f('notifications_user_id_foreign'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('notifications_type_index'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('notifications_status_index'), 'notifications', ['status'], unique=False)
    op.create_index(op.f('notifications_created_at_index'), 'notifications', ['created_at'], unique=False)
    op.alter_column('notifications', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=True)
    op.alter_column('notifications', 'user_id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(unsigned=True),
               existing_nullable=False)
    op.alter_column('notifications', 'id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(unsigned=True),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('notifications', 'sent_at')
    op.drop_column('notifications', 'retry_count')
    op.drop_column('notifications', 'error_message')
    op.drop_column('notifications', 'recipient')
    op.drop_column('notifications', 'data')
    op.drop_column('notifications', 'subject')
    op.drop_column('notifications', 'channel')
    op.drop_constraint(None, 'notification_settings', type_='foreignkey')
    op.drop_constraint(None, 'dropped_domains', type_='foreignkey')
    op.drop_index(op.f('ix_dropped_domains_tld_id'), table_name='dropped_domains')
    op.drop_index(op.f('ix_dropped_domains_id'), table_name='dropped_domains')
    op.drop_index(op.f('ix_dropped_domains_drop_date'), table_name='dropped_domains')
    op.drop_index(op.f('ix_dropped_domains_domain'), table_name='dropped_domains')
    op.drop_index('idx_domain_drop_date', table_name='dropped_domains')
    op.alter_column('dropped_domains', 'domain',
               existing_type=sa.String(length=191),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_index(op.f('ix_domain_histories_domain'), table_name='domain_histories')
    op.drop_constraint(None, 'cron_job_logs', type_='foreignkey')
    op.create_table('domain_filters',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('query_json', mysql.JSON(), nullable=False),
    sa.Column('is_public', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    op.create_index(op.f('domain_filters_user_id_index'), 'domain_filters', ['user_id'], unique=False)
    op.create_index(op.f('domain_filters_is_public_index'), 'domain_filters', ['is_public'], unique=False)
    op.create_table('user_notification_settings',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('email_enabled', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('telegram_enabled', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('webpush_enabled', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('telegram_chat_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=True),
    sa.Column('webpush_endpoint', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('webpush_p256dh', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('webpush_auth', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    op.create_index(op.f('user_notification_settings_user_id_unique'), 'user_notification_settings', ['user_id'], unique=True)
    op.create_table('domain_sources',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), server_default=sa.text("'custom'"), nullable=False),
    sa.Column('description', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('fetch_frequency_minutes', mysql.INTEGER(), server_default=sa.text("'1440'"), autoincrement=False, nullable=False),
    sa.Column('last_run_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    op.create_index(op.f('domain_sources_type_index'), 'domain_sources', ['type'], unique=False)
    op.create_index(op.f('domain_sources_name_unique'), 'domain_sources', ['name'], unique=True)
    op.create_index(op.f('domain_sources_is_active_index'), 'domain_sources', ['is_active'], unique=False)
    op.create_table('user_favorite_domains',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('domain_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    op.create_index(op.f('user_favorite_domains_user_id_index'), 'user_favorite_domains', ['user_id'], unique=False)
    op.create_index(op.f('user_favorite_domains_user_id_domain_id_unique'), 'user_favorite_domains', ['user_id', 'domain_id'], unique=True)
    op.create_index(op.f('user_favorite_domains_domain_id_index'), 'user_favorite_domains', ['domain_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=True),
    sa.Column('ip_address', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45), nullable=True),
    sa.Column('user_agent', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('payload', mysql.LONGTEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('last_activity', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    op.create_index(op.f('sessions_user_id_index'), 'sessions', ['user_id'], unique=False)
    op.create_index(op.f('sessions_last_activity_index'), 'sessions', ['last_activity'], unique=False)
    op.create_table('domain_metrics',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('domain_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('archive_first_seen', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('archive_last_seen', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('archive_snapshots_count', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('ref_domains', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('backlink_quality_score', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('spam_score', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('risk_flags', mysql.JSON(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    op.create_index(op.f('domain_metrics_spam_score_index'), 'domain_metrics', ['spam_score'], unique=False)
    op.create_index(op.f('domain_metrics_ref_domains_index'), 'domain_metrics', ['ref_domains'], unique=False)
    op.create_index(op.f('domain_metrics_domain_id_foreign'), 'domain_metrics', ['domain_id'], unique=False)
    op.create_index(op.f('domain_metrics_backlink_quality_score_index'), 'domain_metrics', ['backlink_quality_score'], unique=False)
    op.create_index(op.f('domain_metrics_archive_snapshots_count_index'), 'domain_metrics', ['archive_snapshots_count'], unique=False)
    op.create_table('domains',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('fqdn', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=True),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('tld', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=True),
    sa.Column('source', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=True),
    sa.Column('status', mysql.ENUM('pending_delete', 'deleted', 'auction'), nullable=True),
    sa.Column('drop_date', mysql.DATETIME(), nullable=True),
    sa.Column('dropped_at', mysql.DATETIME(), nullable=True),
    sa.Column('length', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('brandability_score', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('created_at_registry', mysql.DATETIME(), nullable=True),
    sa.Column('first_seen_at', mysql.DATETIME(), nullable=True),
    sa.Column('last_seen_at', mysql.DATETIME(), nullable=True),
    sa.Column('price', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('currency', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=3), server_default=sa.text("'USD'"), nullable=True),
    sa.Column('backlinks_count', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('referring_domains', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('domain_popularity', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('archive_org_birth', mysql.DATETIME(), nullable=True),
    sa.Column('language', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=5), nullable=True),
    sa.Column('spam_score', mysql.TINYINT(), autoincrement=False, nullable=True),
    sa.Column('is_indexed_google', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    op.create_index(op.f('domains_tld_index'), 'domains', ['tld'], unique=False)
    op.create_index(op.f('domains_status_index'), 'domains', ['status'], unique=False)
    op.create_index(op.f('domains_spam_score_index'), 'domains', ['spam_score'], unique=False)
    op.create_index(op.f('domains_source_index'), 'domains', ['source'], unique=False)
    op.create_index(op.f('domains_name_unique'), 'domains', ['name'], unique=True)
    op.create_index(op.f('domains_fqdn_index'), 'domains', ['fqdn'], unique=False)
    op.create_index(op.f('domains_dropped_at_index'), 'domains', ['dropped_at'], unique=False)
    op.create_index(op.f('domains_drop_date_index'), 'domains', ['drop_date'], unique=False)
    op.create_index(op.f('domains_brandability_score_index'), 'domains', ['brandability_score'], unique=False)
    op.create_index(op.f('domains_backlinks_count_index'), 'domains', ['backlinks_count'], unique=False)
    op.create_table('domain_score_history',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('domain_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('investment_score', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('spam_score', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('captured_at', mysql.TIMESTAMP(), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    op.create_index(op.f('domain_score_history_domain_id_captured_at_index'), 'domain_score_history', ['domain_id', 'captured_at'], unique=False)
    op.create_index(op.f('domain_score_history_captured_at_index'), 'domain_score_history', ['captured_at'], unique=False)
    op.create_table('user_settings',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('theme', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), server_default=sa.text("'light'"), nullable=False),
    sa.Column('language', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    op.create_index(op.f('user_settings_user_id_unique'), 'user_settings', ['user_id'], unique=True)
    op.create_table('migrations',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('migration', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('batch', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    op.create_table('bulk_imports',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('file_path', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('status', mysql.ENUM('pending', 'processing', 'completed', 'failed'), nullable=False),
    sa.Column('result_path', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    op.create_index(op.f('bulk_imports_user_id_foreign'), 'bulk_imports', ['user_id'], unique=False)
    op.create_index(op.f('bulk_imports_status_index'), 'bulk_imports', ['status'], unique=False)
    op.create_index(op.f('bulk_imports_created_at_index'), 'bulk_imports', ['created_at'], unique=False)
    op.create_table('domain_ai_scores',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('domain_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('investment_score', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('valuation_min', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('valuation_mid', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('valuation_max', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ai_decision', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('recommended_usecase', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('summary', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    op.create_index(op.f('domain_ai_scores_valuation_mid_index'), 'domain_ai_scores', ['valuation_mid'], unique=False)
    op.create_index(op.f('domain_ai_scores_investment_score_index'), 'domain_ai_scores', ['investment_score'], unique=False)
    op.create_index(op.f('domain_ai_scores_domain_id_foreign'), 'domain_ai_scores', ['domain_id'], unique=False)
    op.create_index(op.f('domain_ai_scores_ai_decision_index'), 'domain_ai_scores', ['ai_decision'], unique=False)
    op.create_table('watchlists',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('domain_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('notify_drop', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('notify_score_change', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('notify_spam_change', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('notify_market_events', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    op.create_index(op.f('watchlists_user_id_domain_id_unique'), 'watchlists', ['user_id', 'domain_id'], unique=True)
    op.create_index(op.f('watchlists_notify_score_change_index'), 'watchlists', ['notify_score_change'], unique=False)
    op.create_index(op.f('watchlists_notify_drop_index'), 'watchlists', ['notify_drop'], unique=False)
    op.create_index(op.f('watchlists_domain_id_foreign'), 'watchlists', ['domain_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('token', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('email'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    op.create_table('backorders',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('domain_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('status', mysql.ENUM('pending', 'active', 'success', 'failed', 'cancelled'), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('registrar', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=True),
    sa.Column('notes', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('backorder_date', mysql.TIMESTAMP(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    op.create_index(op.f('backorders_user_id_domain_id_unique'), 'backorders', ['user_id', 'domain_id'], unique=True)
    op.create_index(op.f('backorders_status_index'), 'backorders', ['status'], unique=False)
    op.create_index(op.f('backorders_domain_id_index'), 'backorders', ['domain_id'], unique=False)
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_subscription_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_stripe_payment_intent_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_stripe_invoice_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_user_subscriptions_user_id'), table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_stripe_subscription_id'), table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_stripe_customer_id'), table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_plan_id'), table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_id'), table_name='user_subscriptions')
    op.drop_table('user_subscriptions')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_id'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_subscription_plans_name'), table_name='subscription_plans')
    op.drop_index(op.f('ix_subscription_plans_id'), table_name='subscription_plans')
    op.drop_table('subscription_plans')
    # ### end Alembic commands ###









