"""Initial migration for tlds and dropped_domains

Revision ID: ae3452e56c99
Revises: 
Create Date: 2025-12-09 20:30:51.073444

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ae3452e56c99'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tlds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_import_date', sa.Date(), nullable=True),
    sa.Column('last_drop_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tlds_id'), 'tlds', ['id'], unique=False)
    op.create_index(op.f('ix_tlds_name'), 'tlds', ['name'], unique=True)
    op.create_table('dropped_domains',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('domain', sa.String(length=191), nullable=False),  # Reduced for MySQL index compatibility
    sa.Column('tld_id', sa.Integer(), nullable=False),
    sa.Column('drop_date', sa.Date(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('label_count', sa.Integer(), nullable=False),
    sa.Column('charset_type', sa.String(length=20), nullable=False),
    sa.Column('quality_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tld_id'], ['tlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_domain_drop_date', 'dropped_domains', ['domain', 'drop_date'], unique=True)
    op.create_index(op.f('ix_dropped_domains_domain'), 'dropped_domains', ['domain'], unique=False)
    op.create_index(op.f('ix_dropped_domains_drop_date'), 'dropped_domains', ['drop_date'], unique=False)
    op.create_index(op.f('ix_dropped_domains_id'), 'dropped_domains', ['id'], unique=False)
    op.create_index(op.f('ix_dropped_domains_tld_id'), 'dropped_domains', ['tld_id'], unique=False)
    # Note: Other tables in the database are from a different project and should not be dropped
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain_score_history',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('domain_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('investment_score', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('spam_score', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('captured_at', mysql.TIMESTAMP(), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    op.create_index(op.f('domain_score_history_domain_id_captured_at_index'), 'domain_score_history', ['domain_id', 'captured_at'], unique=False)
    op.create_index(op.f('domain_score_history_captured_at_index'), 'domain_score_history', ['captured_at'], unique=False)
    op.create_table('domain_ai_scores',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('domain_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('investment_score', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('valuation_min', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('valuation_mid', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('valuation_max', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ai_decision', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('recommended_usecase', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('summary', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    op.create_index(op.f('domain_ai_scores_valuation_mid_index'), 'domain_ai_scores', ['valuation_mid'], unique=False)
    op.create_index(op.f('domain_ai_scores_investment_score_index'), 'domain_ai_scores', ['investment_score'], unique=False)
    op.create_index(op.f('domain_ai_scores_domain_id_foreign'), 'domain_ai_scores', ['domain_id'], unique=False)
    op.create_index(op.f('domain_ai_scores_ai_decision_index'), 'domain_ai_scores', ['ai_decision'], unique=False)
    op.create_table('domain_metrics',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('domain_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('archive_first_seen', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('archive_last_seen', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('archive_snapshots_count', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('ref_domains', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('backlink_quality_score', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('spam_score', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('risk_flags', mysql.JSON(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    op.create_index(op.f('domain_metrics_spam_score_index'), 'domain_metrics', ['spam_score'], unique=False)
    op.create_index(op.f('domain_metrics_ref_domains_index'), 'domain_metrics', ['ref_domains'], unique=False)
    op.create_index(op.f('domain_metrics_domain_id_foreign'), 'domain_metrics', ['domain_id'], unique=False)
    op.create_index(op.f('domain_metrics_backlink_quality_score_index'), 'domain_metrics', ['backlink_quality_score'], unique=False)
    op.create_index(op.f('domain_metrics_archive_snapshots_count_index'), 'domain_metrics', ['archive_snapshots_count'], unique=False)
    op.create_table('sessions',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=True),
    sa.Column('ip_address', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45), nullable=True),
    sa.Column('user_agent', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('payload', mysql.LONGTEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('last_activity', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    op.create_index(op.f('sessions_user_id_index'), 'sessions', ['user_id'], unique=False)
    op.create_index(op.f('sessions_last_activity_index'), 'sessions', ['last_activity'], unique=False)
    op.create_table('notifications',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('message', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('status', mysql.ENUM('pending', 'sent', 'failed'), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('read_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    op.create_index(op.f('notifications_user_id_foreign'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('notifications_type_index'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('notifications_status_index'), 'notifications', ['status'], unique=False)
    op.create_index(op.f('notifications_created_at_index'), 'notifications', ['created_at'], unique=False)
    op.create_table('user_settings',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('theme', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), server_default=sa.text("'light'"), nullable=False),
    sa.Column('language', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    op.create_index(op.f('user_settings_user_id_unique'), 'user_settings', ['user_id'], unique=True)
    op.create_table('backorders',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('domain_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('status', mysql.ENUM('pending', 'active', 'success', 'failed', 'cancelled'), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('registrar', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=True),
    sa.Column('notes', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('backorder_date', mysql.TIMESTAMP(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    op.create_index(op.f('backorders_user_id_domain_id_unique'), 'backorders', ['user_id', 'domain_id'], unique=True)
    op.create_index(op.f('backorders_status_index'), 'backorders', ['status'], unique=False)
    op.create_index(op.f('backorders_domain_id_index'), 'backorders', ['domain_id'], unique=False)
    op.create_table('bulk_imports',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('file_path', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('status', mysql.ENUM('pending', 'processing', 'completed', 'failed'), nullable=False),
    sa.Column('result_path', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    op.create_index(op.f('bulk_imports_user_id_foreign'), 'bulk_imports', ['user_id'], unique=False)
    op.create_index(op.f('bulk_imports_status_index'), 'bulk_imports', ['status'], unique=False)
    op.create_index(op.f('bulk_imports_created_at_index'), 'bulk_imports', ['created_at'], unique=False)
    op.create_table('migrations',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('migration', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('batch', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    op.create_table('domains',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('fqdn', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=True),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('tld', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=True),
    sa.Column('source', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=True),
    sa.Column('status', mysql.ENUM('pending_delete', 'deleted', 'auction'), nullable=True),
    sa.Column('drop_date', mysql.DATETIME(), nullable=True),
    sa.Column('dropped_at', mysql.DATETIME(), nullable=True),
    sa.Column('length', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('brandability_score', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('created_at_registry', mysql.DATETIME(), nullable=True),
    sa.Column('first_seen_at', mysql.DATETIME(), nullable=True),
    sa.Column('last_seen_at', mysql.DATETIME(), nullable=True),
    sa.Column('price', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('currency', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=3), server_default=sa.text("'USD'"), nullable=True),
    sa.Column('backlinks_count', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('referring_domains', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('domain_popularity', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('archive_org_birth', mysql.DATETIME(), nullable=True),
    sa.Column('language', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=5), nullable=True),
    sa.Column('spam_score', mysql.TINYINT(), autoincrement=False, nullable=True),
    sa.Column('is_indexed_google', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    op.create_index(op.f('domains_tld_index'), 'domains', ['tld'], unique=False)
    op.create_index(op.f('domains_status_index'), 'domains', ['status'], unique=False)
    op.create_index(op.f('domains_spam_score_index'), 'domains', ['spam_score'], unique=False)
    op.create_index(op.f('domains_source_index'), 'domains', ['source'], unique=False)
    op.create_index(op.f('domains_name_unique'), 'domains', ['name'], unique=True)
    op.create_index(op.f('domains_fqdn_index'), 'domains', ['fqdn'], unique=False)
    op.create_index(op.f('domains_dropped_at_index'), 'domains', ['dropped_at'], unique=False)
    op.create_index(op.f('domains_drop_date_index'), 'domains', ['drop_date'], unique=False)
    op.create_index(op.f('domains_brandability_score_index'), 'domains', ['brandability_score'], unique=False)
    op.create_index(op.f('domains_backlinks_count_index'), 'domains', ['backlinks_count'], unique=False)
    op.create_table('users',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('is_admin', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('email_verified_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('password', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('remember_token', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    op.create_index(op.f('users_email_unique'), 'users', ['email'], unique=True)
    op.create_table('watchlists',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('domain_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('notify_drop', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('notify_score_change', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('notify_spam_change', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('notify_market_events', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    op.create_index(op.f('watchlists_user_id_domain_id_unique'), 'watchlists', ['user_id', 'domain_id'], unique=True)
    op.create_index(op.f('watchlists_notify_score_change_index'), 'watchlists', ['notify_score_change'], unique=False)
    op.create_index(op.f('watchlists_notify_drop_index'), 'watchlists', ['notify_drop'], unique=False)
    op.create_index(op.f('watchlists_domain_id_foreign'), 'watchlists', ['domain_id'], unique=False)
    op.create_table('domain_sources',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), server_default=sa.text("'custom'"), nullable=False),
    sa.Column('description', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('fetch_frequency_minutes', mysql.INTEGER(), server_default=sa.text("'1440'"), autoincrement=False, nullable=False),
    sa.Column('last_run_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    op.create_index(op.f('domain_sources_type_index'), 'domain_sources', ['type'], unique=False)
    op.create_index(op.f('domain_sources_name_unique'), 'domain_sources', ['name'], unique=True)
    op.create_index(op.f('domain_sources_is_active_index'), 'domain_sources', ['is_active'], unique=False)
    op.create_table('domain_filters',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('query_json', mysql.JSON(), nullable=False),
    sa.Column('is_public', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    op.create_index(op.f('domain_filters_user_id_index'), 'domain_filters', ['user_id'], unique=False)
    op.create_index(op.f('domain_filters_is_public_index'), 'domain_filters', ['is_public'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('token', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('email'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    op.create_table('user_favorite_domains',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('domain_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    op.create_index(op.f('user_favorite_domains_user_id_index'), 'user_favorite_domains', ['user_id'], unique=False)
    op.create_index(op.f('user_favorite_domains_user_id_domain_id_unique'), 'user_favorite_domains', ['user_id', 'domain_id'], unique=True)
    op.create_index(op.f('user_favorite_domains_domain_id_index'), 'user_favorite_domains', ['domain_id'], unique=False)
    op.create_table('user_notification_settings',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('email_enabled', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('telegram_enabled', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('webpush_enabled', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('telegram_chat_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=True),
    sa.Column('webpush_endpoint', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('webpush_p256dh', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('webpush_auth', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    op.create_index(op.f('user_notification_settings_user_id_unique'), 'user_notification_settings', ['user_id'], unique=True)
    op.drop_index(op.f('ix_dropped_domains_tld_id'), table_name='dropped_domains')
    op.drop_index(op.f('ix_dropped_domains_id'), table_name='dropped_domains')
    op.drop_index(op.f('ix_dropped_domains_drop_date'), table_name='dropped_domains')
    op.drop_index(op.f('ix_dropped_domains_domain'), table_name='dropped_domains')
    op.drop_index('idx_domain_drop_date', table_name='dropped_domains')
    op.drop_table('dropped_domains')
    op.drop_index(op.f('ix_tlds_name'), table_name='tlds')
    op.drop_index(op.f('ix_tlds_id'), table_name='tlds')
    op.drop_table('tlds')
    # ### end Alembic commands ###

